apiVersion: batch/v1
kind: Job
spec:
  template:
    spec:
      containers:
      - name: {{ .Name }}
        image: {{ .Image }}
        imagePullPolicy: IfNotPresent
        command:
          - "/bin/runner"
          - '{{ .Jsn }}'
        env:
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github
                key: token
        volumeMounts:
        - name: data-volume
          mountPath: /data
        resources:
          limits:
            memory: 512Mi
